---
# https://codeclimate.com/
#
engines:
    duplication:
        enabled: true
        config:
            languages:
            - python
    pep8:
        enabled: true
    radon:
        enabled: true
    fixme:
        enabled: true

exclude_paths:
    - tests/**
    - test/**
    - dist/
    - build/
    - setup.cfg
    - MANIFEST.in
    - LICENSE
    - *.txt
    - *.rst

