---
# https://codeclimate.com/
#
engines:
    duplication:
        enabled: true
        config:
            languages:
            - python
    pep8:
        enabled: true
    radon:
        enabled: true
    fixme:
        enabled: true

ratings:
    paths:
        - "src/schvalidator/**"

exclude_paths:
    - tests/**
    - test/**
    - dist/**
    - build/**
    - "*.cfg"
    - "*.in"
    - "LICENSE"
    - "*.txt"
    - "*.rst"

